### PR TITLE
Applied conventions on testing/1.8.0

### PR DESCRIPTION
**Pull request by madebr**
Hello,

`bincrafters-conventions` and `conan-readme-generator` were executed on the branch testing/1.8.0

### CODE REVIEW

**Comment by SSE4** [comment]
@madebr seems like sha256 is incorrect

**Comment by madebr** [comment]
Looks like vpx is not working on macos.
That's probably why there is currently no stable branch.

**Comment by Croydon** [comment]
Not your mistake, but for some reason we do have two Apple Clang 9.1 jobs. Could you please remove one?

**Comment by Croydon** [comment]
Also remove XCode 7.3

**Comment by Croydon** [comment]
Windows and macOS is still failing

**Comment by madebr** [comment]
When building this on my Fedora Linux system, I had to install `yasm`.
Shouldn't `yasm_installer` be added as a build requirement?
Or is it assumed to be installed as part of the basis build system? (in the docker)

**Comment by SSE4** [comment]
@madebr yes, it should be added as build requirement

**Pull request merged**
